version: "3"

services:

  db:
    container_name: db
    environment:
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    image: mariadb
    ports:
      - 8081:3306
    restart: always
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
      - db_backup:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      #XDEBUG_CONFIG: "remote_host=192.168.1.11" # IP local machine
    image: jburger/wordpress-xdebug
    links:
      - db:mysql
    ports:
      - 80:80
    restart: always
    volumes:
      - "./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - "./public:/var/www/html"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8181:80
    restart: always

  wpcli:
    command: "--info"
    container_name: wpcli
    entrypoint: wp
    image: tatemz/wp-cli
    links:
      - db:mysql
    volumes:
      - "./public:/var/www/html"

volumes:
  db_backup:
    # external: true
  # file_backup:
    # external: true
